name: RSpec Test Runner

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: Run tests
        run: |
          npm run test